### ISSUE TITLE
Found a bug when running sprintq

### ISSUE THREAD

**Issue by bfodeke** [hb5co/sprintq#30]
I ran into the error while starting meteor
<code>
W20140912-12:21:32.930(-4)? (STDERR) Consider migrating from `new Meteor.Collection` to `new Mongo.Collection` in: function (){Sprints = new Meteor.Collection("sprints");
W20140912-12:21:33.031(-4)? (STDERR)
W20140912-12:21:33.031(-4)? (STDERR) Sprints.allow({
W20140912-12:21:33.031(-4)? (STDERR)   insert: function (userId, doc) {
W20140912-12:21:33.032(-4)? (STDERR)     // the user must be logged in, and the document must be owned by the user
W20140912-12:21:33.032(-4)? (STDERR)     return (userId);
W20140912-12:21:33.032(-4)? (STDERR)   },
W20140912-12:21:33.033(-4)? (STDERR)   update: function (userId, doc, fields, modifier) {
W20140912-12:21:33.033(-4)? (STDERR)     return (userId);
W20140912-12:21:33.033(-4)? (STDERR)   },
W20140912-12:21:33.033(-4)? (STDERR) });
W20140912-12:21:33.034(-4)? (STDERR)
W20140912-12:21:33.034(-4)? (STDERR) }
</code>

**Comment by mgbellaire** [comment]
Pretty sure this is gone now.  I'm not getting any errors.  @bfodeke, if you need help on anything with your Meteor install, then let me know.
