### ISSUE TITLE
Make escape key for sprint title editing work on Safari also

### ISSUE THREAD

**Issue by mgbellaire** [hb5co/sprintq#53]
Right now, Safari doesn't blur when you hit escape on a form.  The way I, @mgbellaire, would do that is to check for the key press of key num 23 (escape key) in the helper, instead of waiting for 'submit'.

**Comment by shrop** [comment]
Not working for me or @tecto in Chrome either. No auto blur when edit is pressed.

**Comment by mgbellaire** [comment]
Ya, that should auto focus the editor when edit is clicked.
