### ISSUE TITLE
Confirm sprint archiving

### ISSUE THREAD

**Issue by nathanc85** [hb5co/sprintq#83]
In order to avoid archiving sprints by mistake, we need a confirmation pop up...

**Comment by mgbellaire** [comment]
How can I like an issue?

**Comment by mgbellaire** [comment]
I'm going to try and use the [this alertify package](https://atmospherejs.com/ovcharik/alertify) to customize the alert so that it looks a bit better than the default alerts you get out of the browser.

**Comment by mgbellaire** [comment]
I'm sure we can make this a setting if we wanted to.  Maybe we prompt the user whenever they archive a sprint with a checkbox that says "Do not ask this again."  I'm not sure how to customize alertify's alerts, but I'm sure it's possible if we wanted to do that.  At least we can make it a per-user or per-sprintq app setting.

**Comment by mgbellaire** [comment]
@shrop, what do you think?  Think we make this a setting instead of forcing the user to always confirm before they archive?  I have arguments for both methodologies...

**Comment by mgbellaire** [comment]
By the way, I've gotten alertify to work for confirming or denying the archive.  Just haven't committed it yet.

**Comment by shrop** [comment]
nice!

**Comment by shrop** [comment]
I think always do confirm since it it kind of like a delete and I don't think you would do that very often. We can always add a setting later if it become a problem for folks.

**Comment by mgbellaire** [comment]
Archive confirmation alert merged!
